server:
  port: 8080

spring:
  application:
    name: cabinate-api
  mongodb:
    uri: ${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://admin:password123@localhost:27017/cabinate?authSource=admin}}
  data:
    mongodb:
      auto-index-creation: true
